sonar.projectKey=SQLutions-FATEC_API-5-Semestre-Frontend
sonar.organization=sqlutions-fatec

sonar.projectName=API-5-Semestre-Frontend

sonar.sources=src
sonar.exclusions=**/node_modules/**, .next/**, out/**, public/**, **/*.test.js, **/*.test.jsx, **/*.test.ts, **/*.test.tsx
